services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_gateway"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate:v4.18.3
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/payment_gateway?sslmode=disable",
        "up"
      ]
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: .
    environment:
      GRPC_ADDR: ":50051"
      POSTGRES_DSN: "postgres://postgres:postgres@postgres:5432/payment_gateway?sslmode=disable"
    ports:
      - "50051:50051"
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
